import {
  User,
  Department,
  Case,
  CaseMember,
  DocumentRecord,
  EvidenceRecord,
  CustodyEvent,
  AuditRecord,
  SecurityAlert,
  AccessRequest,
  GraphData,
  DigitalSignatureRecord,
} from '../types';

export const MOCK_USERS: Record<string, User> = {
  admin: {
    id: 'user_admin',
    email: 'admin@securevault.local',
    fullName: 'Chief Inspector Arthur Pendelton',
    badgeNumber: 'SV-ADM-001',
    role: 'ADMINISTRATOR',
    departmentId: 'dept_inv',
    departmentName: 'Investigation Division',
    departmentCode: 'INV',
    mfaEnabled: true,
  },
  inv_a: {
    id: 'user_inv_a',
    email: 'inv.a@securevault.local',
    fullName: 'Senior Investigator Sharma',
    badgeNumber: 'SV-INV-104',
    role: 'INVESTIGATOR',
    departmentId: 'dept_inv',
    departmentName: 'Investigation Division',
    departmentCode: 'INV',
    mfaEnabled: true,
  },
  inv_b: {
    id: 'user_inv_b',
    email: 'inv.b@securevault.local',
    fullName: 'Detective Marcus Vance',
    badgeNumber: 'SV-INV-102',
    role: 'INVESTIGATOR',
    departmentId: 'dept_cyber',
    departmentName: 'Cyber Crime Division',
    departmentCode: 'CCD',
    mfaEnabled: false,
  },
  auditor: {
    id: 'user_auditor',
    email: 'auditor@securevault.local',
    fullName: 'Inspector General Elena Rostova',
    badgeNumber: 'SV-AUD-900',
    role: 'AUDITOR',
    departmentId: 'dept_legal',
    departmentName: 'Legal Affairs',
    departmentCode: 'LGL',
    mfaEnabled: true,
  },
};

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'dept_cyber', name: 'Cyber Crime Division', code: 'CCD', description: 'Specialized digital investigations, network forensics, and cyber incident response.' },
  { id: 'dept_inv', name: 'Investigation Division', code: 'INV', description: 'General criminal investigations, field interviews, and evidence collection.' },
  { id: 'dept_legal', name: 'Legal Affairs', code: 'LGL', description: 'Prosecution liaison, court orders, and judicial compliance.' },
  { id: 'dept_forensics', name: 'Digital Forensics', code: 'DFL', description: 'Forensic hardware extraction, memory analysis, and cryptographic authentication.' },
];

export const MOCK_CASES: Case[] = [
  {
    id: 'case_101',
    case_number: 'CASE-2026-101',
    title: 'Project Apex Infrastructure Breach',
    description: 'Unauthorized exfiltration of sensitive telemetry data from state power grid gateway.',
    department_id: 'dept_cyber',
    department_name: 'Cyber Crime Division',
    department_code: 'CCD',
    sensitivity_level: 'SECRET',
    status: 'ACTIVE',
    creator_name: 'Chief Arthur Pendelton',
    member_count: 2,
    document_count: 3,
    evidence_count: 2,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'case_102',
    case_number: 'CASE-2026-102',
    title: 'Financial Ledger Falsification Ring',
    description: 'Systematic double-invoicing and offshore shell routing identified during forensic audit.',
    department_id: 'dept_inv',
    department_name: 'Investigation Division',
    department_code: 'INV',
    sensitivity_level: 'CONFIDENTIAL',
    status: 'ACTIVE',
    creator_name: 'Detective Marcus Vance',
    member_count: 1,
    document_count: 2,
    evidence_count: 1,
    created_at: '2026-08-10T14:30:00Z',
  },
  {
    id: 'case_103',
    case_number: 'CASE-2026-103',
    title: 'Judicial Warrant Intercept Investigation',
    description: 'Tampering investigation into altered bail dispatch logs in district magistrate court.',
    department_id: 'dept_legal',
    department_name: 'Legal Affairs',
    department_code: 'LGL',
    sensitivity_level: 'SECRET',
    status: 'UNDER_REVIEW',
    creator_name: 'Chief Arthur Pendelton',
    member_count: 2,
    document_count: 1,
    evidence_count: 1,
    created_at: '2026-08-15T09:15:00Z',
  },
  {
    id: 'case_104',
    case_number: 'CASE-2026-104',
    title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    description: 'Multi-jurisdiction syndicate manufacturing fake vehicle registration plates (DL-01-AB-1234, MH 12 CD 5678) and forged credentials.',
    department_id: 'dept_inv',
    department_name: 'Investigation Division',
    department_code: 'INV',
    sensitivity_level: 'CONFIDENTIAL',
    status: 'ACTIVE',
    creator_name: 'Chief Arthur Pendelton',
    member_count: 2,
    document_count: 5,
    evidence_count: 3,
    created_at: '2026-08-14T11:20:00Z',
  },
];

export const MOCK_CASE_MEMBERS: Record<string, CaseMember[]> = {
  case_104: [
    {
      id: 'cm_104_1',
      case_id: 'case_104',
      user_id: 'user_inv_a',
      full_name: 'Senior Investigator Sharma',
      email: 'inv.a@securevault.local',
      badge_number: 'SV-INV-104',
      role: 'INVESTIGATOR',
      role_in_case: 'LEAD_INVESTIGATOR',
      assigned_at: '2026-08-14T11:25:00Z',
    },
    {
      id: 'cm_104_2',
      case_id: 'case_104',
      user_id: 'user_admin',
      full_name: 'Chief Inspector Arthur Pendelton',
      email: 'admin@securevault.local',
      badge_number: 'SV-ADM-001',
      role: 'ADMINISTRATOR',
      role_in_case: 'SUPERVISOR',
      assigned_at: '2026-08-14T11:20:00Z',
    },
  ],
  case_102: [
    {
      id: 'cm_102_1',
      case_id: 'case_102',
      user_id: 'user_inv_b',
      full_name: 'Detective Marcus Vance',
      email: 'inv.b@securevault.local',
      badge_number: 'SV-INV-102',
      role: 'INVESTIGATOR',
      role_in_case: 'LEAD_INVESTIGATOR',
      assigned_at: '2026-08-10T14:35:00Z',
    },
  ],
};

export const MOCK_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'doc_fir_104',
    title: 'First Information Report - Case 104',
    original_filename: 'FIR_104.pdf',
    mime_type: 'application/pdf',
    file_size: 1048576,
    sha256_hash: '3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b',
    encryption_algo: 'aes-256-gcm',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    department_id: 'dept_inv',
    department_name: 'Investigation Division',
    owner_id: 'user_inv_a',
    owner_name: 'Senior Investigator Sharma',
    sensitivity_level: 'CONFIDENTIAL',
    current_version: 1,
    status: 'ACTIVE',
    ai_classification: 'FIR',
    ai_confidence: 0.96,
    ai_summary: 'Official First Information Report for Case 104. Pertains to vehicle syndicate registration DL-01-AB-1234, document forgery, and counterfeit credentials.',
    ai_entities: JSON.stringify([
      { type: 'CASE_ID', value: 'CASE-2026-104', confidence: 0.99 },
      { type: 'VEHICLE_NO', value: 'DL-01-AB-1234', confidence: 0.96 },
      { type: 'VEHICLE_NO', value: 'MH 12 CD 5678', confidence: 0.94 },
      { type: 'LEGAL_SECTION', value: 'Section 420 IPC', confidence: 0.98 },
      { type: 'LEGAL_SECTION', value: 'Section 66 IT Act', confidence: 0.97 },
      { type: 'LOCATION', value: 'Sector 62', confidence: 0.91 },
    ]),
    aiEntities: [
      { type: 'CASE_ID', value: 'CASE-2026-104' },
      { type: 'VEHICLE_NO', value: 'DL-01-AB-1234' },
      { type: 'VEHICLE_NO', value: 'MH 12 CD 5678' },
      { type: 'LEGAL_SECTION', value: 'Section 420 IPC' },
      { type: 'LEGAL_SECTION', value: 'Section 66 IT Act' },
      { type: 'LOCATION', value: 'Sector 62' },
    ],
    ocr_extracted_text: `FIRST INFORMATION REPORT (Under Section 154 CrPC)\nPolice Station: Cyber Cell Headquarters, Sector 62\nCase Reference: CASE-2026-104 | FIR No: 104/2026\nDate of Occurrence: 12th August 2026 | Reported: 2026-08-14\nComplainant: Transport Authority Inspector Rajesh K.\nAccused: Unknown syndicate operators linked to vehicle registration DL-01-AB-1234 and MH 12 CD 5678.\nOffences: Section 420 IPC, Section 468 IPC (Forgery), Section 66 IT Act.\nBrief Facts: Recovered duplicate vehicle chassis plates, forged smart cards, and cloned identity documents.\nInvestigating Officer: Senior Investigator Sharma (Badge: SV-INV-104).`,
    is_tampered_demo: 0,
    created_at: '2026-08-14T12:00:00Z',
    updated_at: '2026-08-14T12:00:00Z',
    tags: ['FIR', 'Police', 'Case-104', 'Criminal-Procedure'],
    digitalSignature: {
      id: 'sig_104_fir',
      document_id: 'doc_fir_104',
      signer_id: 'user_admin',
      signer_name: 'Chief Inspector Arthur Pendelton',
      signed_hash: '3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b',
      signature_hex: 'a4b1c2d3e4f5061728394a5b6c7d8e9fa0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1',
      key_fingerprint: 'SHA256:7f8e9d0c1b2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c',
      algorithm: 'RSA-PSS-SHA256-4096',
      certificate_authority: 'SecureVault Root Authority (Internal Justice CA)',
      signed_at: '2026-08-14T12:05:00Z',
    },
    latestIntegrityCheck: {
      id: 'chk_104_fir',
      document_id: 'doc_fir_104',
      registered_hash: '3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b',
      verified_hash: '3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b',
      status: 'VERIFIED',
      verified_by: 'Inspector General Elena Rostova',
      verified_at: '2026-08-25T10:00:00Z',
    },
  },
  {
    id: 'doc_rep_104',
    title: 'Investigation Report: Syndicate Operation & Network',
    original_filename: 'Investigation_Report_104.pdf',
    mime_type: 'application/pdf',
    file_size: 2097152,
    sha256_hash: '8f14e45fceea167a5a36dedd4bea2543add704e46bb25077273fc45ab6409ecf',
    encryption_algo: 'aes-256-gcm',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    department_id: 'dept_inv',
    department_name: 'Investigation Division',
    owner_id: 'user_inv_a',
    owner_name: 'Senior Investigator Sharma',
    sensitivity_level: 'CONFIDENTIAL',
    current_version: 1,
    status: 'ACTIVE',
    ai_classification: 'Investigation Report',
    ai_confidence: 0.98,
    ai_summary: 'Preliminary investigation findings into vehicle evidence DL-01-AB-1234, warehouse raid in Sector 62, and financial trails.',
    aiEntities: [
      { type: 'CASE_ID', value: 'CASE-2026-104' },
      { type: 'VEHICLE_NO', value: 'DL-01-AB-1234' },
      { type: 'LOCATION', value: 'Sector 62' },
      { type: 'AMOUNT', value: '₹48,50,000' },
    ],
    ocr_extracted_text: `PRELIMINARY INVESTIGATION REPORT\nInvestigation Division | Special Operations Group\nSubject: Investigation into vehicle evidence and document forgery in Case 104.\nSuspects Identified: John Doe, alias "Apex Vector", operating out of Sector 62 warehouse.\nRecovered Vehicle Evidence: Black SUV with fake license plate DL-01-AB-1234 equipped with GPS scrambler.\nFinancial Trails: Wire transfers totaling ₹48,50,000 originating from suspect account.\nWitness Statements: Recorded under Section 161 CrPC. Confirms nocturnal deliveries of forged registration certs.\nStatus: Active surveillance ongoing. Immediate forensic validation of recovered memory modules recommended.`,
    is_tampered_demo: 0,
    created_at: '2026-08-16T15:30:00Z',
    updated_at: '2026-08-16T15:30:00Z',
    tags: ['Investigation', 'Report', 'Evidence', 'Case-104', 'Vehicle-Evidence'],
  },
  {
    id: 'doc_ev_104',
    title: 'Evidence Seizure Memo & Property Log',
    original_filename: 'Evidence_Report_104.pdf',
    mime_type: 'application/pdf',
    file_size: 524288,
    sha256_hash: '9c56cc51b374c3ba189210d5b6f4d57f0743b1eee923414004a613232266b81e',
    encryption_algo: 'aes-256-gcm',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    department_id: 'dept_inv',
    department_name: 'Investigation Division',
    owner_id: 'user_inv_a',
    owner_name: 'Senior Investigator Sharma',
    sensitivity_level: 'CONFIDENTIAL',
    current_version: 1,
    status: 'ACTIVE',
    ai_classification: 'Evidence',
    ai_confidence: 0.94,
    ai_summary: 'Seizure memo cataloging physical evidence recovered from Sector 62 including MicroSD card and blank RFID smart cards.',
    aiEntities: [
      { type: 'EVIDENCE_TAG', value: 'EV-104-A' },
      { type: 'VEHICLE_NO', value: 'DL-01-AB-1234' },
      { type: 'SEAL_NO', value: '#9021' },
    ],
    ocr_extracted_text: `SEIZURE MEMO & PHYSICAL EVIDENCE LOG\nCase Reference: CASE-2026-104\nLocation of Recovery: Underground bay 4, Sector 62\nItem No. EV-104-A: MicroSD Card (SanDisk 128GB) retrieved from suspect vehicle DL-01-AB-1234.\nItem No. EV-104-B: 14 Embossed high-security registration plates.\nItem No. EV-104-C: Laser engraving printer and blank PVC RFID chips.\nSeized By: Senior Investigator Sharma in presence of independent panchas.\nSeals Applied: Lacquer seal with SecureVault Tamper-Proof Tag #9021.`,
    is_tampered_demo: 0,
    created_at: '2026-08-18T09:45:00Z',
    updated_at: '2026-08-18T09:45:00Z',
    tags: ['Evidence', 'Seizure', 'Custody', 'Case-104'],
  },
  {
    id: 'doc_for_104',
    title: 'Forensic Lab Report: Chip Cryptanalysis & Firmware Dump',
    original_filename: 'Forensic_Report_104.pdf',
    mime_type: 'application/pdf',
    file_size: 4194304,
    sha256_hash: '2c6d9e1a3f5b7c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c4f8b',
    encryption_algo: 'aes-256-gcm',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    department_id: 'dept_forensics',
    department_name: 'Digital Forensics',
    owner_id: 'user_inv_a',
    owner_name: 'Senior Investigator Sharma',
    sensitivity_level: 'SECRET',
    current_version: 1,
    status: 'ACTIVE',
    ai_classification: 'Forensic Report',
    ai_confidence: 0.99,
    ai_summary: 'Forensic extraction report analyzing bit-stream image of MicroSD card EV-104-A, finding 342 scanned vehicle title deeds and Matrix communications.',
    aiEntities: [
      { type: 'EVIDENCE_TAG', value: 'EV-104-A' },
      { type: 'VEHICLE_NO', value: 'MH 12 CD 5678' },
      { type: 'EXAMINER', value: 'Elena Rostova' },
    ],
    ocr_extracted_text: `DIGITAL FORENSIC SCIENCE LABORATORY\nCyber Forensics & Hardware Analysis Division\nExamination of Evidence Item EV-104-A (SanDisk 128GB MicroSD).\nForensic Imaging: Bit-stream copy created using hardware write-blocker.\nComputed Image SHA-256: 4f8b2c6d9e1a3f5b7c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c\nExtracted Artifacts: 342 scanned vehicle title deeds, encrypted communications via Matrix protocol.\nGPS Telemetry Extraction: Confirms vehicle MH 12 CD 5678 was parked at Sector 62 during the heist.\nExaminer: Lead Forensic Analyst Elena Rostova.`,
    is_tampered_demo: 0,
    created_at: '2026-08-19T14:10:00Z',
    updated_at: '2026-08-19T14:10:00Z',
    tags: ['Forensics', 'Digital-Evidence', 'Lab-Report', 'Case-104'],
  },
  {
    id: 'doc_crt_104',
    title: 'Court Order: Search Warrant & Evidence Admissibility',
    original_filename: 'Court_Order_104.pdf',
    mime_type: 'application/pdf',
    file_size: 786432,
    sha256_hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    encryption_algo: 'aes-256-gcm',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    department_id: 'dept_legal',
    department_name: 'Legal Affairs',
    owner_id: 'user_admin',
    owner_name: 'Chief Inspector Arthur Pendelton',
    sensitivity_level: 'CONFIDENTIAL',
    current_version: 1,
    status: 'ACTIVE',
    ai_classification: 'Court Order',
    ai_confidence: 0.97,
    ai_summary: 'Judicial order under Section 93 CrPC authorizing search and seizure at Sector 62 and certifying electronic admissibility under Section 65B.',
    aiEntities: [
      { type: 'JUDGE', value: 'Hon. V. K. Deshmukh' },
      { type: 'LEGAL_SECTION', value: 'Section 93 CrPC' },
      { type: 'LEGAL_SECTION', value: 'Section 65B Indian Evidence Act' },
    ],
    ocr_extracted_text: `IN THE COURT OF THE PRINCIPAL DISTRICT & SESSIONS JUDGE\nSpecial Cyber Court Jurisdiction | Case Reference: CASE-2026-104\nOrder on Criminal Miscellaneous Application No. 441/2026\nCoram: Honorable Judge V. K. Deshmukh\nUpon hearing Public Prosecutor for Legal Affairs and examining the Case Diary:\n1. Search Warrant granted under Section 93 CrPC for premises located at Sector 62.\n2. Electronic evidence admitted subject to Section 65B Indian Evidence Act certificate.\n3. Custody of vehicle evidence DL-01-AB-1234 remanded to Forensic Science Lab until further orders.\nGiven under my hand and seal of the Court this 20th day of August 2026.`,
    is_tampered_demo: 0,
    created_at: '2026-08-20T11:00:00Z',
    updated_at: '2026-08-20T11:00:00Z',
    tags: ['Court-Order', 'Judicial', 'Legal', 'Case-104'],
    digitalSignature: {
      id: 'sig_104_crt',
      document_id: 'doc_crt_104',
      signer_id: 'user_admin',
      signer_name: 'Chief Inspector Arthur Pendelton',
      signed_hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
      signature_hex: 'e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5061728394a5b6c7d8e9fa0b1c2d3e4f5',
      key_fingerprint: 'SHA256:8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b',
      algorithm: 'RSA-PSS-SHA256-4096',
      certificate_authority: 'SecureVault Root Authority (Internal Justice CA)',
      signed_at: '2026-08-20T11:15:00Z',
    },
  },
];

export const MOCK_EVIDENCE: EvidenceRecord[] = [
  {
    id: 'ev_104_a',
    evidence_number: 'EV-104-A',
    title: 'MicroSD Card (SanDisk 128GB)',
    description: 'Hardware memory module extracted from dash console of suspect vehicle DL-01-AB-1234.',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    document_id: 'doc_for_104',
    current_custodian_id: 'user_auditor',
    custodian_name: 'Inspector General Elena Rostova',
    badge_number: 'SV-AUD-900',
    status: 'FORENSIC_ANALYSIS',
    storage_location: 'FSL Locker #44, Evidence Vault Alpha',
    integrity_hash: '4f8b2c6d9e1a3f5b7c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c',
    collected_at: '2026-08-14T16:00:00Z',
    created_at: '2026-08-14T16:00:00Z',
  },
  {
    id: 'ev_104_b',
    evidence_number: 'EV-104-B',
    title: '14 Embossed High-Security Registration Plates',
    description: 'Counterfeit aluminum registration plates bearing duplicate series (DL-01-AB-1234, MH 12 CD 5678).',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    document_id: 'doc_ev_104',
    current_custodian_id: 'user_inv_a',
    custodian_name: 'Senior Investigator Sharma',
    badge_number: 'SV-INV-104',
    status: 'IN_CUSTODY',
    storage_location: 'Malkhana Armory Box 12-B',
    integrity_hash: '7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
    collected_at: '2026-08-14T16:30:00Z',
    created_at: '2026-08-14T16:30:00Z',
  },
  {
    id: 'ev_104_c',
    evidence_number: 'EV-104-C',
    title: 'Laser Engraving System & Blank RFID PVC Cards',
    description: 'Industrial plate stamping equipment and 200 blank smart cards seized from Sector 62.',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    case_title: 'Operation Nightshade: Vehicle Syndicate & Identity Forgery',
    document_id: 'doc_ev_104',
    current_custodian_id: 'user_inv_a',
    custodian_name: 'Senior Investigator Sharma',
    badge_number: 'SV-INV-104',
    status: 'IN_CUSTODY',
    storage_location: 'Malkhana Heavy Evidence Room #3',
    integrity_hash: '9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e',
    collected_at: '2026-08-14T17:15:00Z',
    created_at: '2026-08-14T17:15:00Z',
  },
];

export const MOCK_CUSTODY_EVENTS: Record<string, CustodyEvent[]> = {
  ev_104_a: [
    {
      id: 'cust_104_1',
      evidence_id: 'ev_104_a',
      case_id: 'case_104',
      previous_custodian: 'Scene of Crime (Vehicle DL-01-AB-1234)',
      new_custodian: 'Senior Investigator Sharma',
      action: 'COLLECTION_AND_SEAL',
      reason: 'Physical recovery during search under Section 93 CrPC.',
      timestamp: '2026-08-14T16:00:00Z',
      performed_by_id: 'user_inv_a',
      performed_by_name: 'Senior Investigator Sharma',
      badge_number: 'SV-INV-104',
      integrity_hash: '4f8b2c6d9e1a3f5b7c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c',
      signature_status: 'VERIFIED',
    },
    {
      id: 'cust_104_2',
      evidence_id: 'ev_104_a',
      case_id: 'case_104',
      previous_custodian: 'Senior Investigator Sharma',
      new_custodian: 'Inspector General Elena Rostova (Forensic Lab)',
      action: 'FORENSIC_TRANSFER',
      reason: 'Remanded for bit-stream disk imaging and cryptographic extraction.',
      timestamp: '2026-08-15T09:30:00Z',
      performed_by_id: 'user_admin',
      performed_by_name: 'Chief Inspector Arthur Pendelton',
      badge_number: 'SV-ADM-001',
      integrity_hash: '4f8b2c6d9e1a3f5b7c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c',
      signature_status: 'VERIFIED',
    },
  ],
};

export const MOCK_AUDIT_LOGS: AuditRecord[] = [
  {
    id: 'audit_gen',
    user_id: 'SYSTEM',
    user_name: 'SecureVault Genesis Kernel',
    action: 'SYSTEM_INITIALIZATION',
    details: 'Cryptographic root ledger anchored. Genesis state established.',
    ip_address: '127.0.0.1',
    timestamp: '2026-08-01T00:00:00Z',
    previous_hash: '0000000000000000000000000000000000000000000000000000000000000000',
    current_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'audit_01',
    user_id: 'user_admin',
    user_name: 'Chief Inspector Arthur Pendelton',
    action: 'CASE_ASSIGNED',
    resource_id: 'case_104',
    resource_type: 'CASE',
    case_id: 'case_104',
    details: 'Senior Investigator Sharma assigned as Lead on CASE-2026-104.',
    ip_address: '10.0.4.12',
    timestamp: '2026-08-14T11:25:00Z',
    previous_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    current_hash: '8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b',
  },
  {
    id: 'audit_02',
    user_id: 'user_inv_a',
    user_name: 'Senior Investigator Sharma',
    action: 'DOCUMENT_UPLOADED',
    resource_id: 'doc_fir_104',
    resource_type: 'DOCUMENT',
    case_id: 'case_104',
    details: 'First Information Report uploaded with AES-256-GCM envelope encryption and SHA-256 fingerprint.',
    ip_address: '10.0.4.55',
    timestamp: '2026-08-14T12:00:00Z',
    previous_hash: '8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b',
    current_hash: '7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c',
  },
  {
    id: 'audit_03',
    user_id: 'user_admin',
    user_name: 'Chief Inspector Arthur Pendelton',
    action: 'DIGITAL_SIGNATURE_APPLIED',
    resource_id: 'doc_fir_104',
    resource_type: 'DOCUMENT',
    case_id: 'case_104',
    details: 'Applied RSA-PSS-SHA256-4096 judicial verification signature.',
    ip_address: '10.0.4.12',
    timestamp: '2026-08-14T12:05:00Z',
    previous_hash: '7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c',
    current_hash: '9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d',
  },
  {
    id: 'audit_04',
    user_id: 'user_inv_b',
    user_name: 'Detective Marcus Vance',
    action: 'ACCESS_DENIED_UNAUTHORIZED',
    resource_id: 'doc_fir_104',
    resource_type: 'DOCUMENT',
    case_id: 'case_104',
    details: 'Unauthorized document access blocked (HTTP 403): Marcus Vance is not assigned to CASE-2026-104.',
    ip_address: '10.0.5.88',
    timestamp: '2026-08-15T14:22:00Z',
    previous_hash: '9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d',
    current_hash: '1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e',
  },
];

export const MOCK_SECURITY_ALERTS: SecurityAlert[] = [
  {
    id: 'alert_01',
    alert_type: 'UNAUTHORIZED_CROSS_CASE_PROBING',
    severity: 'HIGH',
    user_id: 'user_inv_b',
    user_name: 'Detective Marcus Vance',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    description: 'Multiple unauthorized read attempts detected on Case 104 evidence by unassigned officer Marcus Vance.',
    reasons: ['User does not possess active Case 104 roster clearance', 'High frequency polling detected on confidential documents'],
    risk_score: 75,
    is_resolved: 0,
    created_at: '2026-08-15T14:25:00Z',
  },
  {
    id: 'alert_02',
    alert_type: 'BULK_DECRYPTION_VELOCITY',
    severity: 'MEDIUM',
    user_id: 'user_inv_a',
    user_name: 'Senior Investigator Sharma',
    case_id: 'case_104',
    case_number: 'CASE-2026-104',
    description: 'Rapid sequential decryption of 4 confidential case documents within 45 seconds.',
    reasons: ['Exceeds standard human reading velocity baseline', 'Verified legitimate during court submission prep'],
    risk_score: 40,
    is_resolved: 1,
    created_at: '2026-08-18T10:12:00Z',
  },
];

export const MOCK_GRAPH_DATA: GraphData = {
  caseId: 'case_104',
  nodes: [
    { id: 'case_104', label: 'CASE-2026-104 (Operation Nightshade)', type: 'CASE', sensitivity: 'CONFIDENTIAL' },
    { id: 'doc_fir_104', label: 'FIR 104/2026', type: 'DOCUMENT', sensitivity: 'CONFIDENTIAL' },
    { id: 'doc_rep_104', label: 'Investigation Report 104', type: 'DOCUMENT', sensitivity: 'CONFIDENTIAL' },
    { id: 'doc_for_104', label: 'Forensic Lab Report', type: 'DOCUMENT', sensitivity: 'SECRET' },
    { id: 'ev_104_a', label: 'MicroSD 128GB (EV-104-A)', type: 'EVIDENCE', sensitivity: 'SECRET' },
    { id: 'ev_104_b', label: '14 Embossed Number Plates (EV-104-B)', type: 'EVIDENCE', sensitivity: 'CONFIDENTIAL' },
    { id: 'ent_veh_1', label: 'Vehicle DL-01-AB-1234', type: 'VEHICLE' },
    { id: 'ent_veh_2', label: 'Vehicle MH 12 CD 5678', type: 'VEHICLE' },
    { id: 'ent_sus_1', label: 'John Doe ("Apex Vector")', type: 'PERSON' },
    { id: 'ent_loc_1', label: 'Sector 62 Underground Bay 4', type: 'LOCATION' },
    { id: 'ent_org_1', label: 'Transport Authority', type: 'ORGANIZATION' },
  ],
  edges: [
    { id: 'e1', source: 'case_104', target: 'doc_fir_104', label: 'CONTAINS' },
    { id: 'e2', source: 'case_104', target: 'doc_rep_104', label: 'CONTAINS' },
    { id: 'e3', source: 'case_104', target: 'doc_for_104', label: 'CONTAINS' },
    { id: 'e4', source: 'case_104', target: 'ev_104_a', label: 'HAS_EVIDENCE' },
    { id: 'e5', source: 'case_104', target: 'ev_104_b', label: 'HAS_EVIDENCE' },
    { id: 'e6', source: 'doc_fir_104', target: 'ent_veh_1', label: 'IDENTIFIES' },
    { id: 'e7', source: 'doc_fir_104', target: 'ent_veh_2', label: 'IDENTIFIES' },
    { id: 'e8', source: 'doc_rep_104', target: 'ent_sus_1', label: 'SUSPECT_NAMED' },
    { id: 'e9', source: 'doc_rep_104', target: 'ent_loc_1', label: 'SCENE_OF_CRIME' },
    { id: 'e10', source: 'ev_104_a', target: 'ent_veh_1', label: 'RECOVERED_FROM' },
    { id: 'e11', source: 'doc_for_104', target: 'ev_104_a', label: 'ANALYZES' },
  ],
  stats: {
    totalNodes: 11,
    totalEdges: 11,
    casesCount: 1,
  },
};
